spring:
  application:
    name: ai-coder-backend
server:
  port: 8080
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.littlewin.aicoder.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn